/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import java.util.ArrayList;
import models.Produto;

/**
 *
 * @author 182220015
 */
public class FormTextArea extends javax.swing.JFrame {

  ArrayList<Produto> produtos = new ArrayList<>();

  /**
   * Creates new form NewJFrame
   */
  public FormTextArea() {
    initComponents();
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    labelCodigo = new javax.swing.JLabel();
    labelNome = new javax.swing.JLabel();
    labelPreco = new javax.swing.JLabel();
    inputPreco = new javax.swing.JTextField();
    inputCodigo = new javax.swing.JTextField();
    inputNome = new javax.swing.JTextField();
    labelNota = new javax.swing.JLabel();
    jScrollPane1 = new javax.swing.JScrollPane();
    textareaNota = new javax.swing.JTextArea();
    btnIncluir = new javax.swing.JButton();
    btnTotal = new javax.swing.JButton();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

    labelCodigo.setText("Código do produto:");

    labelNome.setText("Nome do produto:");

    labelPreco.setText("Preço do produto:");

    inputPreco.setBackground(new java.awt.Color(255, 255, 255));

    inputCodigo.setBackground(new java.awt.Color(255, 255, 255));

    inputNome.setBackground(new java.awt.Color(255, 255, 255));

    labelNota.setBackground(new java.awt.Color(255, 255, 255));
    labelNota.setText("Nota:");

    jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));

    textareaNota.setBackground(new java.awt.Color(255, 255, 255));
    textareaNota.setColumns(20);
    textareaNota.setRows(5);
    jScrollPane1.setViewportView(textareaNota);

    btnIncluir.setBackground(new java.awt.Color(20, 50, 240));
    btnIncluir.setForeground(new java.awt.Color(255, 255, 255));
    btnIncluir.setText("Incluir");
    btnIncluir.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        btnIncluirMouseClicked(evt);
      }
    });

    btnTotal.setBackground(new java.awt.Color(120, 200, 120));
    btnTotal.setForeground(new java.awt.Color(255, 255, 255));
    btnTotal.setText("Total");
    btnTotal.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        btnTotalMouseClicked(evt);
      }
    });

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addGap(14, 14, 14)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
          .addComponent(labelNota)
          .addComponent(inputNome, javax.swing.GroupLayout.DEFAULT_SIZE, 276, Short.MAX_VALUE)
          .addComponent(inputPreco)
          .addComponent(inputCodigo, javax.swing.GroupLayout.DEFAULT_SIZE, 276, Short.MAX_VALUE)
          .addComponent(labelPreco)
          .addComponent(labelNome)
          .addComponent(labelCodigo)
          .addComponent(jScrollPane1))
        .addGap(35, 35, 35)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(btnIncluir, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(btnTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addContainerGap(16, Short.MAX_VALUE))
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addGap(15, 15, 15)
        .addComponent(labelCodigo)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(inputCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(labelNome)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(inputNome, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addComponent(labelPreco)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(inputPreco, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addComponent(labelNota)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addGroup(layout.createSequentialGroup()
            .addComponent(btnIncluir, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addComponent(btnTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
        .addContainerGap(18, Short.MAX_VALUE))
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void btnIncluirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnIncluirMouseClicked
    String codigo = inputCodigo.getText();
    String nome = inputNome.getText();
    Float preco = Float.parseFloat(inputPreco.getText());

    produtos.add(new Produto(codigo, nome, preco));

    textareaNota.setText(listaProdutos());
  }//GEN-LAST:event_btnIncluirMouseClicked

  private void btnTotalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTotalMouseClicked
    float total = 0;

    for (Produto p : produtos) {
      total += p.getPreco();
    }

    textareaNota.setText(String.format("%s\n------------------------------------------------------\nTotal R$                                   %.2f", textareaNota.getText(), total));
  }//GEN-LAST:event_btnTotalMouseClicked

  public String listaProdutos() {
    String lista = "";

    for (int i = 0; i < produtos.size(); i++) {
      Produto p = produtos.get(i);
      lista += String.format("%d -- %s\n", (i + 1), p);
    }

    return lista;
  }

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex) {
      java.util.logging.Logger.getLogger(FormTextArea.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
      java.util.logging.Logger.getLogger(FormTextArea.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
      java.util.logging.Logger.getLogger(FormTextArea.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(FormTextArea.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>
    //</editor-fold>
    //</editor-fold>
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
      public void run() {
        new FormTextArea().setVisible(true);
      }
    });
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton btnIncluir;
  private javax.swing.JButton btnTotal;
  private javax.swing.JTextField inputCodigo;
  private javax.swing.JTextField inputNome;
  private javax.swing.JTextField inputPreco;
  private javax.swing.JScrollPane jScrollPane1;
  private javax.swing.JLabel labelCodigo;
  private javax.swing.JLabel labelNome;
  private javax.swing.JLabel labelNota;
  private javax.swing.JLabel labelPreco;
  private javax.swing.JTextArea textareaNota;
  // End of variables declaration//GEN-END:variables
}
