/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import models.Produto;

/**
 *
 * @author 182220015
 */
public class FormTable extends javax.swing.JFrame {

  ArrayList<Produto> produtos = new ArrayList<>();
  DefaultTableModel modelTabelaNota;

  /**
   * Creates new form NewJFrame
   */
  public FormTable() {
    initComponents();
    modelTabelaNota = (DefaultTableModel) tabelaNota.getModel();
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    labelCodigo = new javax.swing.JLabel();
    labelNome = new javax.swing.JLabel();
    labelPreco = new javax.swing.JLabel();
    inputPreco = new javax.swing.JTextField();
    inputCodigo = new javax.swing.JTextField();
    inputNome = new javax.swing.JTextField();
    labelNota = new javax.swing.JLabel();
    btnIncluir = new javax.swing.JButton();
    btnTotal = new javax.swing.JButton();
    scrollPane = new javax.swing.JScrollPane();
    tabelaNota = new javax.swing.JTable();
    labelTotal = new javax.swing.JLabel();
    inputTotal = new javax.swing.JTextField();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

    labelCodigo.setText("Código do produto:");

    labelNome.setText("Nome do produto:");

    labelPreco.setText("Preço do produto:");

    inputPreco.setBackground(new java.awt.Color(255, 255, 255));

    inputCodigo.setBackground(new java.awt.Color(255, 255, 255));

    inputNome.setBackground(new java.awt.Color(255, 255, 255));

    labelNota.setBackground(new java.awt.Color(255, 255, 255));
    labelNota.setText("Nota:");

    btnIncluir.setBackground(new java.awt.Color(20, 50, 240));
    btnIncluir.setForeground(new java.awt.Color(255, 255, 255));
    btnIncluir.setText("Incluir");
    btnIncluir.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        btnIncluirMouseClicked(evt);
      }
    });

    btnTotal.setBackground(new java.awt.Color(120, 200, 120));
    btnTotal.setForeground(new java.awt.Color(255, 255, 255));
    btnTotal.setText("Total");
    btnTotal.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        btnTotalMouseClicked(evt);
      }
    });

    tabelaNota.setBackground(new java.awt.Color(255, 255, 255));
    tabelaNota.setModel(new javax.swing.table.DefaultTableModel(
      new Object [][] {

      },
      new String [] {
        "Índice", "Código", "Nome", "Preço"
      }
    ) {
      Class[] types = new Class [] {
        java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
      };
      boolean[] canEdit = new boolean [] {
        false, false, false, false
      };

      public Class getColumnClass(int columnIndex) {
        return types [columnIndex];
      }

      public boolean isCellEditable(int rowIndex, int columnIndex) {
        return canEdit [columnIndex];
      }
    });
    scrollPane.setViewportView(tabelaNota);

    labelTotal.setText("Total:");

    inputTotal.setBackground(new java.awt.Color(255, 255, 255));

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addGap(14, 14, 14)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(layout.createSequentialGroup()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
              .addComponent(labelNota)
              .addComponent(inputNome, javax.swing.GroupLayout.DEFAULT_SIZE, 276, Short.MAX_VALUE)
              .addComponent(inputPreco)
              .addComponent(inputCodigo, javax.swing.GroupLayout.DEFAULT_SIZE, 276, Short.MAX_VALUE)
              .addComponent(labelPreco)
              .addComponent(labelNome)
              .addComponent(labelCodigo))
            .addGap(41, 41, 41)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                .addComponent(btnTotal, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE)
                .addComponent(inputTotal))
              .addComponent(btnIncluir, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addComponent(labelTotal)))
          .addComponent(scrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addContainerGap(14, Short.MAX_VALUE))
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addGap(15, 15, 15)
        .addComponent(labelCodigo)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(inputCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(btnIncluir, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(labelNome)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(inputNome, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(btnTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(labelPreco)
          .addComponent(labelTotal))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(inputPreco, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(inputTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addComponent(labelNota)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(scrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addContainerGap(16, Short.MAX_VALUE))
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void btnIncluirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnIncluirMouseClicked
    String codigo = inputCodigo.getText();
    String nome = inputNome.getText();
    Float preco = Float.parseFloat(inputPreco.getText());

    produtos.add(new Produto(codigo, nome, preco));
    listaProdutos();
  }//GEN-LAST:event_btnIncluirMouseClicked

  private void btnTotalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTotalMouseClicked
    float total = 0;

    for (Produto p : produtos) {
      total += p.getPreco();
    }

    inputTotal.setText(String.format("R$ %.2f", total));
  }//GEN-LAST:event_btnTotalMouseClicked

  public void listaProdutos() {
    modelTabelaNota.getDataVector().clear();

    for (int i = 0; i < produtos.size(); i++) {
      Produto p = produtos.get(i);
      modelTabelaNota.addRow(new Object[]{(i + 1), p.getCodigo(), p.getNome(), String.format("R$ %.2f", p.getPreco())});
    }
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton btnIncluir;
  private javax.swing.JButton btnTotal;
  private javax.swing.JTextField inputCodigo;
  private javax.swing.JTextField inputNome;
  private javax.swing.JTextField inputPreco;
  private javax.swing.JTextField inputTotal;
  private javax.swing.JLabel labelCodigo;
  private javax.swing.JLabel labelNome;
  private javax.swing.JLabel labelNota;
  private javax.swing.JLabel labelPreco;
  private javax.swing.JLabel labelTotal;
  private javax.swing.JScrollPane scrollPane;
  private javax.swing.JTable tabelaNota;
  // End of variables declaration//GEN-END:variables
}
