/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import javax.swing.JOptionPane;

/**
 *
 * @author 182220015
 */
public class Form extends javax.swing.JFrame {

  int tentativas = 3;

  /**
   * Creates new form Form
   */
  public Form() {
    initComponents();
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    labelNome = new javax.swing.JLabel();
    inputNome = new javax.swing.JTextField();
    inputEmail = new javax.swing.JTextField();
    labelEmail = new javax.swing.JLabel();
    btnLimpar = new javax.swing.JButton();
    btnEntrar = new javax.swing.JButton();
    labelSenha = new javax.swing.JLabel();
    inputSenha = new javax.swing.JPasswordField();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
    setTitle("Form -- GUI");

    labelNome.setText("Nome:");

    inputNome.setBackground(new java.awt.Color(255, 255, 255));
    inputNome.setText("Digite seu nome");
    inputNome.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        inputNomeMouseClicked(evt);
      }
    });

    inputEmail.setBackground(new java.awt.Color(255, 255, 255));
    inputEmail.setText("Digite seu e-mail");
    inputEmail.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        inputEmailMouseClicked(evt);
      }
    });

    labelEmail.setText("E-mail:");

    btnLimpar.setBackground(new java.awt.Color(190, 50, 25));
    btnLimpar.setForeground(new java.awt.Color(255, 255, 255));
    btnLimpar.setText("Limpar");
    btnLimpar.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        btnLimparMouseClicked(evt);
      }
    });

    btnEntrar.setBackground(new java.awt.Color(25, 50, 125));
    btnEntrar.setForeground(new java.awt.Color(255, 255, 255));
    btnEntrar.setText("Entrar");
    btnEntrar.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        btnEntrarMouseClicked(evt);
      }
    });

    labelSenha.setText("Senha:");

    inputSenha.setBackground(new java.awt.Color(255, 255, 255));
    inputSenha.setText("**********");
    inputSenha.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        inputSenhaMouseClicked(evt);
      }
    });

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addGap(17, 17, 17)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(labelSenha)
          .addGroup(layout.createSequentialGroup()
            .addComponent(btnEntrar, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addComponent(btnLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
          .addComponent(labelEmail)
          .addComponent(labelNome)
          .addComponent(inputNome, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
            .addComponent(inputSenha, javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(inputEmail, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)))
        .addContainerGap(21, Short.MAX_VALUE))
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addGap(15, 15, 15)
        .addComponent(labelNome)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(inputNome, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(labelEmail)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(inputEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(labelSenha)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(inputSenha, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
        .addGap(18, 18, 18)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(btnLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(btnEntrar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addContainerGap(31, Short.MAX_VALUE))
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void btnLimparMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLimparMouseClicked
    inputNome.setText("");
    inputEmail.setText("");
  }//GEN-LAST:event_btnLimparMouseClicked

  private void inputNomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_inputNomeMouseClicked
    if (inputNome.getText().trim().equals("Digite seu nome"))
      inputNome.setText("");
  }//GEN-LAST:event_inputNomeMouseClicked

  private void inputEmailMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_inputEmailMouseClicked
    if (inputEmail.getText().trim().equals("Digite seu e-mail"))
      inputEmail.setText("");
  }//GEN-LAST:event_inputEmailMouseClicked

  private void inputSenhaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_inputSenhaMouseClicked
    if (String.valueOf(inputSenha.getPassword()).equals("**********"))
      inputSenha.setText("");
  }//GEN-LAST:event_inputSenhaMouseClicked

  private void btnEntrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEntrarMouseClicked
    String senha = String.valueOf(inputSenha.getPassword());
    String errorMessage = (tentativas == 0 ? "Sistema bloqueado!" : String.format("Senha incorreta!\nTentativas restantes: %d", tentativas));

    if (tentativas == 0) {
      JOptionPane.showMessageDialog(this, errorMessage,
              "Formulário - Erro ao fazer login", JOptionPane.ERROR_MESSAGE);
      return;
    }

    if (!senha.equals("123")) {
      tentativas--;
      JOptionPane.showMessageDialog(this, errorMessage,
              "Formulário - Senha incorreta", JOptionPane.WARNING_MESSAGE);
      return;
    }

    JOptionPane.showMessageDialog(this, String.format("Seja bem vindo(a) %s!", inputNome.getText()),
            "Formulário - Login realizado", JOptionPane.PLAIN_MESSAGE);

  }//GEN-LAST:event_btnEntrarMouseClicked

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex) {
      java.util.logging.Logger.getLogger(Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
      java.util.logging.Logger.getLogger(Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
      java.util.logging.Logger.getLogger(Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
      public void run() {
        new Form().setVisible(true);
      }
    });
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton btnEntrar;
  private javax.swing.JButton btnLimpar;
  private javax.swing.JTextField inputEmail;
  private javax.swing.JTextField inputNome;
  private javax.swing.JPasswordField inputSenha;
  private javax.swing.JLabel labelEmail;
  private javax.swing.JLabel labelNome;
  private javax.swing.JLabel labelSenha;
  // End of variables declaration//GEN-END:variables
}
